---
title: "My Credit Predictions - Final Project 475"
author: "Connor Davis"
date: "5/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(regclass)
library(caret)
library(caretEnsemble)
library(nnet)
library(neuralnet)
library(e1071)
library(glmnet)
library(gbm)
library(pROC)
library(parallel)
library(doParallel)
library(regclass)
library(caret)
library(parallel)
library(doParallel)
library(kernlab)
library(fpp3)
```


```{r}
credits <- read.csv("credit.csv")
credits$period <- 1:492
credits <- tsibble(credits, index = period)
autoplot(credits)
```

```{r}
credits <- credits %>%
  mutate(diff_series = difference(credit_in_millions))

credits %>%
  autoplot(diff_series)
```

```{r}
train_df <- head(credits, nrow(credits) - 12)
test_df <- tail(credits, 12)
```

```{r}
fit <- train_df %>%
  model(ARIMA(credit_in_millions))
report(fit)

fit <- train_df %>% 
  stretch_tsibble(.step = 24, .init = 48) %>%
  model(
    arima111 = ARIMA(credit_in_millions ~ pdq(1, 1, 1) + PDQ(0, 1, 1)),
    arima213 = ARIMA(credit_in_millions ~ pdq(2, 1, 3) + PDQ(0, 1, 1)),
    arima411 = ARIMA(credit_in_millions ~ pdq(4, 1, 1) + PDQ(0, 1, 1)),
    arima312 = ARIMA(credit_in_millions ~ pdq(3, 1, 2) + PDQ(0, 1, 1)), #best rmse
  )



fit %>% 
  forecast(h = 12) %>% 
  accuracy(train_df) %>% 
  arrange(RMSE)
```

```{r}
fit <- train_df %>% 
  model(arima312 = ARIMA(credit_in_millions ~ pdq(3, 1, 2) + PDQ(0, 1, 1)))

report(fit)
```

```{r}
fit %>%
  select(arima312) %>%
  gg_tsresiduals(lag = 48)
```

```{r}
forecast(fit, h = 12) %>%
  filter(.model == 'arima312') %>%
  autoplot(train_df)
```

```{r}
pred <- fit %>%
  forecast(train_df)
pred <- pred$.mean
pred <- pred[1:12]
pred
```


```{r}
rmse <- function(y_pred, y_actual) {
  sqrt(mean((y_pred - y_actual)^2))
}
```

```{r}
rmse(pred, test_df$credit_in_millions)
```
```{r}
predictions <- data.frame(
  Month = test_df$period,
  CreditPredictions = pred
)

# Change FILENAME.csv to a nice name to keep organized
# Don't lose good predictions because of poor naming
write.csv(
  predictions,
  file = "predictions.csv",
  row.names = FALSE
)
```

